### ISSUE TITLE
Install Docker desktop fail

### ISSUE THREAD

**Issue by weizjajj** [docker/desktop-linux#210]
### Description

After install docker desktop on ubnuntu 24.04,when I start it, failed,error:
![截图 2024-04-27 17-55-32](https://github.com/docker/desktop-linux/assets/167891451/6ce60551-3845-4acc-9c86-21b42db8cd62)

### Reproduce

cannot start docker -desktop

### Expected behavior

Docker\ Desktop.stderr.log :
[2024-04-27T07:11:53.763332271Z] [15505:0427/151153.763219:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
[2024-04-27T07:11:54.612057136Z] [15505:0427/151154.611957:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[2024-04-27T07:11:54.958973796Z] Uncaught exception…
[2024-04-27T07:11:54.958993850Z] Error: 14 UNAVAILABLE: No connection established. Last error: connect ENOENT /home/weizj/.docker/harmonia.docker.com/harmonia_alpha.docker.com/daemon.grpc.sock (2024-04-27T07:11:54.256Z)
[2024-04-27T07:11:54.958999151Z]     at t.callErrorFromStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:621661)
[2024-04-27T07:11:54.959002705Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649272)
[2024-04-27T07:11:54.959013310Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:642299)
[2024-04-27T07:11:54.959016532Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:2:729619
[2024-04-27T07:11:54.959019992Z]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[2024-04-27T07:11:54.959022516Z] for call at
[2024-04-27T07:11:54.959024909Z]     at s.makeServerStreamRequest (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649039)
[2024-04-27T07:11:54.959027172Z]     at s.cloudEngineWatch (/opt/docker-desktop/resources/app.asar/build/electron.js:2:714169)
[2024-04-27T07:11:54.959029396Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:108946)
[2024-04-27T07:11:54.959031597Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:100745)
[2024-04-27T07:11:54.959033762Z]     at Hs (/opt/docker-desktop/resources/app.asar/build/electron.js:8:584299)
[2024-04-27T07:11:54.959035933Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:8:861285
[2024-04-27T07:11:54.959038177Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-------------------------------------------------------------------------------->8
[2024-04-27T07:12:39.038228925Z] [16262:0427/151239.038154:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
[2024-04-27T07:12:39.959047961Z] [16262:0427/151239.958972:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[2024-04-27T07:12:40.160692664Z] Uncaught exception…
[2024-04-27T07:12:40.160720524Z] Error: 14 UNAVAILABLE: No connection established. Last error: connect ENOENT /home/weizj/.docker/harmonia.docker.com/harmonia_alpha.docker.com/daemon.grpc.sock (2024-04-27T07:12:39.528Z)
[2024-04-27T07:12:40.160726745Z]     at t.callErrorFromStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:621661)
[2024-04-27T07:12:40.160730594Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649272)
[2024-04-27T07:12:40.160734180Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:642299)
[2024-04-27T07:12:40.160737991Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:2:729619
[2024-04-27T07:12:40.160741471Z]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[2024-04-27T07:12:40.160744916Z] for call at
[2024-04-27T07:12:40.160748206Z]     at s.makeServerStreamRequest (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649039)
[2024-04-27T07:12:40.160751033Z]     at s.cloudEngineWatch (/opt/docker-desktop/resources/app.asar/build/electron.js:2:714169)
[2024-04-27T07:12:40.160754041Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:108946)
[2024-04-27T07:12:40.160766813Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:100745)
[2024-04-27T07:12:40.160768996Z]     at Hs (/opt/docker-desktop/resources/app.asar/build/electron.js:8:584299)
[2024-04-27T07:12:40.160770795Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:8:861285
[2024-04-27T07:12:40.160772582Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-------------------------------------------------------------------------------->8
[2024-04-27T07:14:41.618928530Z] [16649:0427/151441.618849:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
[2024-04-27T07:14:42.783472459Z] Uncaught exception…
[2024-04-27T07:14:42.783491603Z] Error: 14 UNAVAILABLE: No connection established. Last error: connect ENOENT /home/weizj/.docker/harmonia.docker.com/harmonia_alpha.docker.com/daemon.grpc.sock (2024-04-27T07:14:42.114Z)
[2024-04-27T07:14:42.783494948Z]     at t.callErrorFromStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:621661)
[2024-04-27T07:14:42.783497549Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649272)
[2024-04-27T07:14:42.783499723Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:642299)
[2024-04-27T07:14:42.783501831Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:2:729619
[2024-04-27T07:14:42.783504430Z]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[2024-04-27T07:14:42.783506664Z] for call at
[2024-04-27T07:14:42.783509029Z]     at s.makeServerStreamRequest (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649039)
[2024-04-27T07:14:42.783517406Z]     at s.cloudEngineWatch (/opt/docker-desktop/resources/app.asar/build/electron.js:2:714169)
[2024-04-27T07:14:42.783519721Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:108946)
[2024-04-27T07:14:42.783521890Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:100745)
[2024-04-27T07:14:42.783523933Z]     at Hs (/opt/docker-desktop/resources/app.asar/build/electron.js:8:584299)
[2024-04-27T07:14:42.783525983Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:8:861285
[2024-04-27T07:14:42.783528062Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-------------------------------------------------------------------------------->8
[2024-04-27T09:49:43.559059307Z] [19367:0427/174943.558978:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
[2024-04-27T09:49:44.455091119Z] [19367:0427/174944.455000:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[2024-04-27T09:49:44.731887460Z] Uncaught exception…
[2024-04-27T09:49:44.731910451Z] Error: 14 UNAVAILABLE: No connection established. Last error: connect ENOENT /home/weizj/.docker/harmonia.docker.com/harmonia_alpha.docker.com/daemon.grpc.sock (2024-04-27T09:49:44.068Z)
[2024-04-27T09:49:44.731918228Z]     at t.callErrorFromStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:621661)
[2024-04-27T09:49:44.731922124Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649272)
[2024-04-27T09:49:44.731941951Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:642299)
[2024-04-27T09:49:44.731944720Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:2:729619
[2024-04-27T09:49:44.731947347Z]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[2024-04-27T09:49:44.731950098Z] for call at
[2024-04-27T09:49:44.731952679Z]     at s.makeServerStreamRequest (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649039)
[2024-04-27T09:49:44.731955136Z]     at s.cloudEngineWatch (/opt/docker-desktop/resources/app.asar/build/electron.js:2:714169)
[2024-04-27T09:49:44.731957532Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:108946)
[2024-04-27T09:49:44.731960011Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:100745)
[2024-04-27T09:49:44.731962368Z]     at Hs (/opt/docker-desktop/resources/app.asar/build/electron.js:8:584299)
[2024-04-27T09:49:44.731964673Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:8:861285
[2024-04-27T09:49:44.731967024Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-------------------------------------------------------------------------------->8
[2024-04-27T09:51:26.731203819Z] [20976:0427/175126.731033:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
[2024-04-27T09:51:27.585833108Z] [20976:0427/175127.585737:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[2024-04-27T09:51:27.855620080Z] Uncaught exception…
[2024-04-27T09:51:27.855648271Z] Error: 14 UNAVAILABLE: No connection established. Last error: connect ENOENT /home/weizj/.docker/harmonia.docker.com/harmonia_alpha.docker.com/daemon.grpc.sock (2024-04-27T09:51:27.224Z)
[2024-04-27T09:51:27.855654449Z]     at t.callErrorFromStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:621661)
[2024-04-27T09:51:27.855657767Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649272)
[2024-04-27T09:51:27.855660658Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:642299)
[2024-04-27T09:51:27.855663539Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:2:729619
[2024-04-27T09:51:27.855666794Z]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[2024-04-27T09:51:27.855670197Z] for call at
[2024-04-27T09:51:27.855673406Z]     at s.makeServerStreamRequest (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649039)
[2024-04-27T09:51:27.855676325Z]     at s.cloudEngineWatch (/opt/docker-desktop/resources/app.asar/build/electron.js:2:714169)
[2024-04-27T09:51:27.855679292Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:108946)
[2024-04-27T09:51:27.855682696Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:100745)
[2024-04-27T09:51:27.855686953Z]     at Hs (/opt/docker-desktop/resources/app.asar/build/electron.js:8:584299)
[2024-04-27T09:51:27.855691463Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:8:861285
[2024-04-27T09:51:27.855695551Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-------------------------------------------------------------------------------->8
[2024-04-27T09:55:01.248204123Z] [21492:0427/175501.248091:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
[2024-04-27T09:55:02.367748251Z] Uncaught exception…
[2024-04-27T09:55:02.367770186Z] Error: 14 UNAVAILABLE: No connection established. Last error: connect ENOENT /home/weizj/.docker/harmonia.docker.com/harmonia_alpha.docker.com/daemon.grpc.sock (2024-04-27T09:55:01.761Z)
[2024-04-27T09:55:02.367776351Z]     at t.callErrorFromStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:621661)
[2024-04-27T09:55:02.367779466Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649272)
[2024-04-27T09:55:02.367782127Z]     at Object.onReceiveStatus (/opt/docker-desktop/resources/app.asar/build/electron.js:2:642299)
[2024-04-27T09:55:02.367784216Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:2:729619
[2024-04-27T09:55:02.367786380Z]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[2024-04-27T09:55:02.367788474Z] for call at
[2024-04-27T09:55:02.367790529Z]     at s.makeServerStreamRequest (/opt/docker-desktop/resources/app.asar/build/electron.js:2:649039)
[2024-04-27T09:55:02.367792489Z]     at s.cloudEngineWatch (/opt/docker-desktop/resources/app.asar/build/electron.js:2:714169)
[2024-04-27T09:55:02.367794392Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:108946)
[2024-04-27T09:55:02.367796278Z]     at e.watchCloudEngines (/opt/docker-desktop/resources/app.asar/build/electron.js:2:100745)
[2024-04-27T09:55:02.367798165Z]     at Hs (/opt/docker-desktop/resources/app.asar/build/electron.js:8:584299)
[2024-04-27T09:55:02.367800087Z]     at /opt/docker-desktop/resources/app.asar/build/electron.js:8:861285
[2024-04-27T09:55:02.367801996Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### docker version

```bash
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.10
 Version:           26.1.0
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        9714adc
 Built:             Mon Apr 22 17:06:54 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       c8af8eb
  Built:            Mon Apr 22 17:06:54 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     /usr/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /usr/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /usr/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 1
 Server Version: 26.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-31-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.22GiB
 Name: weizj-y7000p
 ID: 91ac8790-e7bd-4269-99dd-7f935607c121
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

20AE81B7-A3D2-46B4-8EF1-1354BCC0F25D/20240427095803

**Comment by andinianst93** [comment]
I encountered the same problem after upgrading from Ubuntu 22 to Ubuntu 24. Do we have to wait until the new version of Docker Desktop release?

**Comment by FlexLV** [comment]
Same here I spent over 4 hours trying to fix it I get it opened but in diagnose 
/opt/docker-desktop/bin/com.docker.diagnose check
I got this one even though I got vm started docker is launched but in docker desktop it just waits for docker engine to start even if its started.
Please investigate the following 1 issue:

1 : The test: can a VM be started?
    Failed with: vm has not started: failed to open init.log: open /home/ernests/.docker/desktop/log/vm/init.log: no such file or directory

**Comment by dangbert** [comment]
I'm also experiencing this issue on Ubuntu 24.04

````bash
# system info:
$ docker --version
Docker version 27.1.1, build 6312585

$ uname -a
Linux thinker 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# here I try to launch docker desktop manually to see the logs
$ /opt/docker-desktop/Docker\ Desktop
[10616:0902/141447.708699:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
````


I was able to work around this to fix my docker by running `docker context use default` which I think tells it to effectively ignore the installation of Docker Desktop.  So I can run docker from the commandline afterwards but the docker desktop UI has never worked.
